environ:
  seed: 5
  deterministic: False
model:
  name: "dorn"
  pretrained_model:
  params:
    ord_num: 90
    gamma: -0.97
    beta: 90.0
    scene: "Kitti"
    discretization: "SID"
    pretrained: True
data:
  name: "Kitti"
  split: ["trainval", "selected_val"]
  path: '/data/wangxin/KITTI'
  tr_crop_size: [385, 513]
  te_crop_size: [385, 513]
  imagenet_normalize: True
solver:
  epochs: 14
  batch_size: 4
  step_decay: 1
  optimizer:
    name: 'SGD'
    params:
      lr: 0.001
      momentum: 0.9
      weight_decay: 0.0005
  lr_policy:
    name: 'poly'
    params:
      gamma: 0.9
      n_iteration: 300636
apex:
  amp_used: False
  opt_level: "O1"
  keep_batchnorm_fp32:
  loss_scale:
vis_config:
  name: "dorn"
  horizontally: False
snap:
  path: "/data/snap_dir/monodepth"


